apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pgsql
  name: pgsql
spec:
  containers:
  - name: pgsql
    env:
      - name: POSTGRES_USER
        valueFrom:
          configMapKeyRef:
            name: zabbix-cm
            key: POSTGRES_USER

      - name: POSTGRES_DB
        valueFrom:
          configMapKeyRef:
            name: zabbix-cm
            key: POSTGRES_DB

      - name: POSTGRES_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: zabbix-cm
            key: POSTGRES_PASSWORD
    image: docker.io/library/postgres:16.6
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    volumeMounts:
    - mountPath: /var/lib/postgresql/data:Z
      name: pgsql-db-vol
    ports:
    - containerPort: 5432
      hostPort: 5432
      protocol: TCP
  volumes:
  - hostPath:
      path: /opt/pgsql-db-vol
      type: Directory
    name: pgsql-db-vol
status: {}