apiVersion: v1
kind: Pod
metadata:
  labels:
    app: zabbix
  name: zabbix-web-nginx-pgsql
spec:
  containers:
  - name: zabbix-web-nginx-pgsql
    env:
      - name: DB_SERVER_HOST
        valueFrom:
          configMapKeyRef:
            name: zabbix-cm
            key: DB_SERVER_HOST

      - name: DB_SERVER_PORT
        valueFrom:
          configMapKeyRef:
            name: zabbix-cm
            key: DB_SERVER_PORT

      - name: POSTGRES_USER
        valueFrom:
          configMapKeyRef:
            name: zabbix-cm
            key: POSTGRES_USER

      - name: POSTGRES_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: zabbix-cm
            key: POSTGRES_PASSWORD

      - name: POSTGRES_DB
        valueFrom:
          configMapKeyRef:
            name: zabbix-cm
            key: POSTGRES_DB
    image: docker.io/zabbix/zabbix-web-nginx-pgsql:7.0.2-alpine
    ports:
    - containerPort: 8080
      hostPort: 8080
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    volumeMounts:
    - mountPath: /etc/ssl/nginx:Z
      name: zb-web-nginx-vol
    - mountPath: /etc/zabbix/web/certs:Z
      name: zb-web-certs-vol
  volumes:
  - hostPath:
      path: /opt/zb-web-nginx-vol
      type: Directory
    name: zb-web-nginx-vol
  - hostPath:
      path: /opt/zb-web-certs-vol
      type: Directory
    name: zb-web-certs-vol
status: {}